services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    environment:
      - ZONE=${ZONE}
      - SUBDOMAIN=${SUBDOMAIN}
      - PROXIED=${PROXIED}
      - API_KEY=${API_KEY}
    restart: no
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
