services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vault.local
    volumes:
      - ./vw-data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vault.local`)
      - traefik.http.routers.vaultwarden.entrypoints=web
      - traefik.http.routers.vaultwarden.service=vaultwarden-svc
      - traefik.http.services.vaultwarden-svc.loadbalancer.healthcheck.path=/alive
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
